name: zHealth
version: '1.0.0'
main: org.import_os.zHealth.ZHealth
api-version: '1.20'

commands:
  sethealth:
    description: Sets the Player's Health
    usage: /sethealth <player> <health>
    permission: zhealth.sethealth

  sethunger:
    description: Sets the Player's Hunger
    usage: /sethunger <player> <hunger>
    permission: zhealth.sethunger

  health:
    description: Shows the Player's Health
    usage: /health <player>
    permission: zhealth.health

  hunger:
    description: Shows the Player's Hunger
    usage: /hunger <player>
    permission: zhealth.hunger
